stages:
  - publish

variables:
  UV_VERSION: "0.5"
  PYTHON_VERSION: "3.12"
  BASE_LAYER: bookworm-slim
  # GitLab CI creates a separate mountpoint for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy
  UV_PUBLISH_USERNAME: "__token__"
  UV_PUBLISH_PASSWORD: "$UV_PUBLISH_PASSWORD_LIGANDPARAM"

uv:
  stage: publish
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  script:
    - uv build
    - uv publish
  rules:
    - if: $CI_COMMIT_TAG
